all: class.exe classtmp.exe construc.exe inherita.exe mult_inh.exe nested.exe operover.exe polymorp.exe private.exe purevirt.exe statmeth.exe this.exe virtual.exe

.cpp.exe:
	bcc $<

clean:
	del *.exe
	del *.obj
